//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeffBourdier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeffBourdier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centiframe.
        /// </summary>
        internal static string Centiframe {
            get {
                return ResourceManager.GetString("Centiframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Mode.
        /// </summary>
        internal static string ChannelMode {
            get {
                return ResourceManager.GetString("ChannelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel of an event using running status cannot be changed arbitrarily..
        /// </summary>
        internal static string ChannelNotChanged {
            get {
                return ResourceManager.GetString("ChannelNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Pressure (Aftertouch).
        /// </summary>
        internal static string ChannelPressure {
            get {
                return ResourceManager.GetString("ChannelPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) | {2} bytes of data.
        /// </summary>
        internal static string ChunkCommentFormat {
            get {
                return ResourceManager.GetString("ChunkCommentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk type must be exactly 4 characters..
        /// </summary>
        internal static string ChunkTypeLength {
            get {
                return ResourceManager.GetString("ChunkTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI clocks per metronome click.
        /// </summary>
        internal static string ClocksPerClick {
            get {
                return ResourceManager.GetString("ClocksPerClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Change.
        /// </summary>
        internal static string ControlChange {
            get {
                return ResourceManager.GetString("ControlChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Select.
        /// </summary>
        internal static string Controller0 {
            get {
                return ResourceManager.GetString("Controller0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulation wheel or lever.
        /// </summary>
        internal static string Controller1 {
            get {
                return ResourceManager.GetString("Controller1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string Controller10 {
            get {
                return ResourceManager.GetString("Controller10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Parameter Number LSB.
        /// </summary>
        internal static string Controller100 {
            get {
                return ResourceManager.GetString("Controller100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Parameter Number MSB.
        /// </summary>
        internal static string Controller101 {
            get {
                return ResourceManager.GetString("Controller101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Controller.
        /// </summary>
        internal static string Controller11 {
            get {
                return ResourceManager.GetString("Controller11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Control 1.
        /// </summary>
        internal static string Controller12 {
            get {
                return ResourceManager.GetString("Controller12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Control 2.
        /// </summary>
        internal static string Controller13 {
            get {
                return ResourceManager.GetString("Controller13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 1.
        /// </summary>
        internal static string Controller16 {
            get {
                return ResourceManager.GetString("Controller16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 2.
        /// </summary>
        internal static string Controller17 {
            get {
                return ResourceManager.GetString("Controller17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 3.
        /// </summary>
        internal static string Controller18 {
            get {
                return ResourceManager.GetString("Controller18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 4.
        /// </summary>
        internal static string Controller19 {
            get {
                return ResourceManager.GetString("Controller19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath Controller.
        /// </summary>
        internal static string Controller2 {
            get {
                return ResourceManager.GetString("Controller2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 0.
        /// </summary>
        internal static string Controller32 {
            get {
                return ResourceManager.GetString("Controller32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 1.
        /// </summary>
        internal static string Controller33 {
            get {
                return ResourceManager.GetString("Controller33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 2.
        /// </summary>
        internal static string Controller34 {
            get {
                return ResourceManager.GetString("Controller34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 3.
        /// </summary>
        internal static string Controller35 {
            get {
                return ResourceManager.GetString("Controller35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 4.
        /// </summary>
        internal static string Controller36 {
            get {
                return ResourceManager.GetString("Controller36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 5.
        /// </summary>
        internal static string Controller37 {
            get {
                return ResourceManager.GetString("Controller37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 6.
        /// </summary>
        internal static string Controller38 {
            get {
                return ResourceManager.GetString("Controller38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 7.
        /// </summary>
        internal static string Controller39 {
            get {
                return ResourceManager.GetString("Controller39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot controller.
        /// </summary>
        internal static string Controller4 {
            get {
                return ResourceManager.GetString("Controller4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 8.
        /// </summary>
        internal static string Controller40 {
            get {
                return ResourceManager.GetString("Controller40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 9.
        /// </summary>
        internal static string Controller41 {
            get {
                return ResourceManager.GetString("Controller41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 10.
        /// </summary>
        internal static string Controller42 {
            get {
                return ResourceManager.GetString("Controller42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 11.
        /// </summary>
        internal static string Controller43 {
            get {
                return ResourceManager.GetString("Controller43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 12.
        /// </summary>
        internal static string Controller44 {
            get {
                return ResourceManager.GetString("Controller44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 13.
        /// </summary>
        internal static string Controller45 {
            get {
                return ResourceManager.GetString("Controller45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 14.
        /// </summary>
        internal static string Controller46 {
            get {
                return ResourceManager.GetString("Controller46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 15.
        /// </summary>
        internal static string Controller47 {
            get {
                return ResourceManager.GetString("Controller47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 16.
        /// </summary>
        internal static string Controller48 {
            get {
                return ResourceManager.GetString("Controller48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 17.
        /// </summary>
        internal static string Controller49 {
            get {
                return ResourceManager.GetString("Controller49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portamento time.
        /// </summary>
        internal static string Controller5 {
            get {
                return ResourceManager.GetString("Controller5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 18.
        /// </summary>
        internal static string Controller50 {
            get {
                return ResourceManager.GetString("Controller50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 19.
        /// </summary>
        internal static string Controller51 {
            get {
                return ResourceManager.GetString("Controller51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 20.
        /// </summary>
        internal static string Controller52 {
            get {
                return ResourceManager.GetString("Controller52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 21.
        /// </summary>
        internal static string Controller53 {
            get {
                return ResourceManager.GetString("Controller53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 22.
        /// </summary>
        internal static string Controller54 {
            get {
                return ResourceManager.GetString("Controller54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 23.
        /// </summary>
        internal static string Controller55 {
            get {
                return ResourceManager.GetString("Controller55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 24.
        /// </summary>
        internal static string Controller56 {
            get {
                return ResourceManager.GetString("Controller56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 25.
        /// </summary>
        internal static string Controller57 {
            get {
                return ResourceManager.GetString("Controller57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 26.
        /// </summary>
        internal static string Controller58 {
            get {
                return ResourceManager.GetString("Controller58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 27.
        /// </summary>
        internal static string Controller59 {
            get {
                return ResourceManager.GetString("Controller59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry MSB.
        /// </summary>
        internal static string Controller6 {
            get {
                return ResourceManager.GetString("Controller6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 28.
        /// </summary>
        internal static string Controller60 {
            get {
                return ResourceManager.GetString("Controller60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 29.
        /// </summary>
        internal static string Controller61 {
            get {
                return ResourceManager.GetString("Controller61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 30.
        /// </summary>
        internal static string Controller62 {
            get {
                return ResourceManager.GetString("Controller62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB for value 31.
        /// </summary>
        internal static string Controller63 {
            get {
                return ResourceManager.GetString("Controller63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustain/Damper pedal.
        /// </summary>
        internal static string Controller64 {
            get {
                return ResourceManager.GetString("Controller64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portamento On/Off.
        /// </summary>
        internal static string Controller65 {
            get {
                return ResourceManager.GetString("Controller65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostenuto.
        /// </summary>
        internal static string Controller66 {
            get {
                return ResourceManager.GetString("Controller66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft pedal.
        /// </summary>
        internal static string Controller67 {
            get {
                return ResourceManager.GetString("Controller67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legato Footswitch.
        /// </summary>
        internal static string Controller68 {
            get {
                return ResourceManager.GetString("Controller68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold 2.
        /// </summary>
        internal static string Controller69 {
            get {
                return ResourceManager.GetString("Controller69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Volume.
        /// </summary>
        internal static string Controller7 {
            get {
                return ResourceManager.GetString("Controller7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 1.
        /// </summary>
        internal static string Controller70 {
            get {
                return ResourceManager.GetString("Controller70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 2.
        /// </summary>
        internal static string Controller71 {
            get {
                return ResourceManager.GetString("Controller71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 3.
        /// </summary>
        internal static string Controller72 {
            get {
                return ResourceManager.GetString("Controller72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 4.
        /// </summary>
        internal static string Controller73 {
            get {
                return ResourceManager.GetString("Controller73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 5.
        /// </summary>
        internal static string Controller74 {
            get {
                return ResourceManager.GetString("Controller74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 6.
        /// </summary>
        internal static string Controller75 {
            get {
                return ResourceManager.GetString("Controller75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 7.
        /// </summary>
        internal static string Controller76 {
            get {
                return ResourceManager.GetString("Controller76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 8.
        /// </summary>
        internal static string Controller77 {
            get {
                return ResourceManager.GetString("Controller77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 9.
        /// </summary>
        internal static string Controller78 {
            get {
                return ResourceManager.GetString("Controller78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Controller 10.
        /// </summary>
        internal static string Controller79 {
            get {
                return ResourceManager.GetString("Controller79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Controller8 {
            get {
                return ResourceManager.GetString("Controller8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 5.
        /// </summary>
        internal static string Controller80 {
            get {
                return ResourceManager.GetString("Controller80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 6.
        /// </summary>
        internal static string Controller81 {
            get {
                return ResourceManager.GetString("Controller81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 7.
        /// </summary>
        internal static string Controller82 {
            get {
                return ResourceManager.GetString("Controller82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Purpose Controller # 8.
        /// </summary>
        internal static string Controller83 {
            get {
                return ResourceManager.GetString("Controller83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portamento Control.
        /// </summary>
        internal static string Controller84 {
            get {
                return ResourceManager.GetString("Controller84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects 1 Depth.
        /// </summary>
        internal static string Controller91 {
            get {
                return ResourceManager.GetString("Controller91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects 2 Depth.
        /// </summary>
        internal static string Controller92 {
            get {
                return ResourceManager.GetString("Controller92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects 3 Depth.
        /// </summary>
        internal static string Controller93 {
            get {
                return ResourceManager.GetString("Controller93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects 4 Depth.
        /// </summary>
        internal static string Controller94 {
            get {
                return ResourceManager.GetString("Controller94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects 5 Depth.
        /// </summary>
        internal static string Controller95 {
            get {
                return ResourceManager.GetString("Controller95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data increment.
        /// </summary>
        internal static string Controller96 {
            get {
                return ResourceManager.GetString("Controller96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data decrement.
        /// </summary>
        internal static string Controller97 {
            get {
                return ResourceManager.GetString("Controller97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Registered Parameter Number LSB.
        /// </summary>
        internal static string Controller98 {
            get {
                return ResourceManager.GetString("Controller98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Registered Parameter Number MSB.
        /// </summary>
        internal static string Controller99 {
            get {
                return ResourceManager.GetString("Controller99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller number.
        /// </summary>
        internal static string ControllerNumber {
            get {
                return ResourceManager.GetString("ControllerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control value.
        /// </summary>
        internal static string ControlValue {
            get {
                return ResourceManager.GetString("ControlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Notice.
        /// </summary>
        internal static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue Point.
        /// </summary>
        internal static string CuePoint {
            get {
                return ResourceManager.GetString("CuePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta-time.
        /// </summary>
        internal static string DeltaTime {
            get {
                return ResourceManager.GetString("DeltaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta-time division.
        /// </summary>
        internal static string DeltaTimeDivision {
            get {
                return ResourceManager.GetString("DeltaTimeDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time signature denominator.
        /// </summary>
        internal static string Denominator {
            get {
                return ResourceManager.GetString("Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Track.
        /// </summary>
        internal static string EndOfTrack {
            get {
                return ResourceManager.GetString("EndOfTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to escape.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Format:.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 (one multi-channel track).
        /// </summary>
        internal static string Format0 {
            get {
                return ResourceManager.GetString("Format0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 (one or more simultaneous tracks).
        /// </summary>
        internal static string Format1 {
            get {
                return ResourceManager.GetString("Format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 (one or more independent tracks).
        /// </summary>
        internal static string Format2 {
            get {
                return ResourceManager.GetString("Format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SMPTE format (frames per second):.
        /// </summary>
        internal static string FramesPerSecond {
            get {
                return ResourceManager.GetString("FramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string FramesPerSecond24 {
            get {
                return ResourceManager.GetString("FramesPerSecond24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string FramesPerSecond25 {
            get {
                return ResourceManager.GetString("FramesPerSecond25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 drop frame.
        /// </summary>
        internal static string FramesPerSecond29 {
            get {
                return ResourceManager.GetString("FramesPerSecond29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string FramesPerSecond30 {
            get {
                return ResourceManager.GetString("FramesPerSecond30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header chunk.
        /// </summary>
        internal static string HeaderChunk {
            get {
                return ResourceManager.GetString("HeaderChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format {0} | {1} tracks | {2}.
        /// </summary>
        internal static string HeaderDataFormat {
            get {
                return ResourceManager.GetString("HeaderDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;title&gt;MIDIopsy Help&lt;/title&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;Jeff Bourdier&quot; /&gt;
        ///    &lt;style&gt;
        ///      h2 { text-align: center; border-bottom: 1px solid; }
        ///      table { margin: auto; border-collapse: collapse; }
        ///      table, th, td { border: 1px solid black; padding: 4px; }
        ///      th { background-color: silver; }
        ///      h4 { border-top: 1px solid; text-align: center; }
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h2&gt;MIDIopsy Help [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Name.
        /// </summary>
        internal static string InstrumentName {
            get {
                return ResourceManager.GetString("InstrumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status byte..
        /// </summary>
        internal static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid variable-length quantity..
        /// </summary>
        internal static string InvalidVLQ {
            get {
                return ResourceManager.GetString("InvalidVLQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Signature.
        /// </summary>
        internal static string KeySignature {
            get {
                return ResourceManager.GetString("KeySignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyric.
        /// </summary>
        internal static string Lyric {
            get {
                return ResourceManager.GetString("Lyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker.
        /// </summary>
        internal static string Marker {
            get {
                return ResourceManager.GetString("Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type.
        /// </summary>
        internal static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta-event | {0,-19} | {1,3} bytes.
        /// </summary>
        internal static string MetaEventFormat {
            get {
                return ResourceManager.GetString("MetaEventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta-event type.
        /// </summary>
        internal static string MetaEventType {
            get {
                return ResourceManager.GetString("MetaEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data length for a {0} meta-event must be at least {1} bytes..
        /// </summary>
        internal static string MetaLengthFormat {
            get {
                return ResourceManager.GetString("MetaLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Metrical time.
        /// </summary>
        internal static string MetricalTime {
            get {
                return ResourceManager.GetString("MetricalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to microseconds per quarter note.
        /// </summary>
        internal static string MicrosecondsPerQuarterNote {
            get {
                return ResourceManager.GetString("MicrosecondsPerQuarterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Channel Prefix.
        /// </summary>
        internal static string MidiChannelPrefix {
            get {
                return ResourceManager.GetString("MidiChannelPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Files (*.midi;*.mid;*.rmi;*.smf)|*.midi;*.mid;*.rmi;*.smf.
        /// </summary>
        internal static string MidiFiles {
            get {
                return ResourceManager.GetString("MidiFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Header.
        /// </summary>
        internal static string MidiHeader {
            get {
                return ResourceManager.GetString("MidiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MIDIopsy {
            get {
                object obj = ResourceManager.GetObject("MIDIopsy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sound Off.
        /// </summary>
        internal static string Mode120 {
            get {
                return ResourceManager.GetString("Mode120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Controllers.
        /// </summary>
        internal static string Mode121 {
            get {
                return ResourceManager.GetString("Mode121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Control.
        /// </summary>
        internal static string Mode122 {
            get {
                return ResourceManager.GetString("Mode122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Notes Off.
        /// </summary>
        internal static string Mode123 {
            get {
                return ResourceManager.GetString("Mode123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omni Mode Off.
        /// </summary>
        internal static string Mode124 {
            get {
                return ResourceManager.GetString("Mode124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omni Mode On.
        /// </summary>
        internal static string Mode125 {
            get {
                return ResourceManager.GetString("Mode125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono Mode On.
        /// </summary>
        internal static string Mode126 {
            get {
                return ResourceManager.GetString("Mode126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poly Mode On.
        /// </summary>
        internal static string Mode127 {
            get {
                return ResourceManager.GetString("Mode127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note number.
        /// </summary>
        internal static string NoteNumber {
            get {
                return ResourceManager.GetString("NoteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Off.
        /// </summary>
        internal static string NoteOff {
            get {
                return ResourceManager.GetString("NoteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note On.
        /// </summary>
        internal static string NoteOn {
            get {
                return ResourceManager.GetString("NoteOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notated 32nd-notes per MIDI quarter note.
        /// </summary>
        internal static string NotesPerQuarterNote {
            get {
                return ResourceManager.GetString("NotesPerQuarterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers of more than 4 bytes (32 bits) are not supported..
        /// </summary>
        internal static string NumberNotSupported {
            get {
                return ResourceManager.GetString("NumberNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Number of tracks:.
        /// </summary>
        internal static string NumberOfTracks {
            get {
                return ResourceManager.GetString("NumberOfTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time signature numerator.
        /// </summary>
        internal static string Numerator {
            get {
                return ResourceManager.GetString("Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch Bend Change.
        /// </summary>
        internal static string PitchBend {
            get {
                return ResourceManager.GetString("PitchBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch bend change value.
        /// </summary>
        internal static string PitchBendChangeValue {
            get {
                return ResourceManager.GetString("PitchBendChangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyphonic Key Pressure (Aftertouch).
        /// </summary>
        internal static string PolyKeyPressure {
            get {
                return ResourceManager.GetString("PolyKeyPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure value.
        /// </summary>
        internal static string PressureValue {
            get {
                return ResourceManager.GetString("PressureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Change.
        /// </summary>
        internal static string ProgramChange {
            get {
                return ResourceManager.GetString("ProgramChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program number.
        /// </summary>
        internal static string ProgramNumber {
            get {
                return ResourceManager.GetString("ProgramNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number.
        /// </summary>
        internal static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequencer-Specific Meta-Event.
        /// </summary>
        internal static string SequencerSpecificMetaEvent {
            get {
                return ResourceManager.GetString("SequencerSpecificMetaEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence/Track Name.
        /// </summary>
        internal static string SequenceTrackName {
            get {
                return ResourceManager.GetString("SequenceTrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Tempo.
        /// </summary>
        internal static string SetTempo {
            get {
                return ResourceManager.GetString("SetTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMPTE Offset.
        /// </summary>
        internal static string SmpteOffset {
            get {
                return ResourceManager.GetString("SmpteOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Grand Piano.
        /// </summary>
        internal static string Sound0 {
            get {
                return ResourceManager.GetString("Sound0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Acoustic Piano.
        /// </summary>
        internal static string Sound1 {
            get {
                return ResourceManager.GetString("Sound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Box.
        /// </summary>
        internal static string Sound10 {
            get {
                return ResourceManager.GetString("Sound10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 5 (brightness).
        /// </summary>
        internal static string Sound100 {
            get {
                return ResourceManager.GetString("Sound100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 6 (goblins).
        /// </summary>
        internal static string Sound101 {
            get {
                return ResourceManager.GetString("Sound101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 7 (echoes).
        /// </summary>
        internal static string Sound102 {
            get {
                return ResourceManager.GetString("Sound102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 8 (sci-fi).
        /// </summary>
        internal static string Sound103 {
            get {
                return ResourceManager.GetString("Sound103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitar.
        /// </summary>
        internal static string Sound104 {
            get {
                return ResourceManager.GetString("Sound104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banjo.
        /// </summary>
        internal static string Sound105 {
            get {
                return ResourceManager.GetString("Sound105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shamisen.
        /// </summary>
        internal static string Sound106 {
            get {
                return ResourceManager.GetString("Sound106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koto.
        /// </summary>
        internal static string Sound107 {
            get {
                return ResourceManager.GetString("Sound107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalimba.
        /// </summary>
        internal static string Sound108 {
            get {
                return ResourceManager.GetString("Sound108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag pipe.
        /// </summary>
        internal static string Sound109 {
            get {
                return ResourceManager.GetString("Sound109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibraphone.
        /// </summary>
        internal static string Sound11 {
            get {
                return ResourceManager.GetString("Sound11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiddle.
        /// </summary>
        internal static string Sound110 {
            get {
                return ResourceManager.GetString("Sound110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shanai.
        /// </summary>
        internal static string Sound111 {
            get {
                return ResourceManager.GetString("Sound111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinkle Bell.
        /// </summary>
        internal static string Sound112 {
            get {
                return ResourceManager.GetString("Sound112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agogo.
        /// </summary>
        internal static string Sound113 {
            get {
                return ResourceManager.GetString("Sound113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Drums.
        /// </summary>
        internal static string Sound114 {
            get {
                return ResourceManager.GetString("Sound114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woodblock.
        /// </summary>
        internal static string Sound115 {
            get {
                return ResourceManager.GetString("Sound115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiko Drum.
        /// </summary>
        internal static string Sound116 {
            get {
                return ResourceManager.GetString("Sound116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic Tom.
        /// </summary>
        internal static string Sound117 {
            get {
                return ResourceManager.GetString("Sound117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synth Drum.
        /// </summary>
        internal static string Sound118 {
            get {
                return ResourceManager.GetString("Sound118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Cymbal.
        /// </summary>
        internal static string Sound119 {
            get {
                return ResourceManager.GetString("Sound119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marimba.
        /// </summary>
        internal static string Sound12 {
            get {
                return ResourceManager.GetString("Sound12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar Fret Noise.
        /// </summary>
        internal static string Sound120 {
            get {
                return ResourceManager.GetString("Sound120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath Noise.
        /// </summary>
        internal static string Sound121 {
            get {
                return ResourceManager.GetString("Sound121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seashore.
        /// </summary>
        internal static string Sound122 {
            get {
                return ResourceManager.GetString("Sound122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird Tweet.
        /// </summary>
        internal static string Sound123 {
            get {
                return ResourceManager.GetString("Sound123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Ring.
        /// </summary>
        internal static string Sound124 {
            get {
                return ResourceManager.GetString("Sound124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        internal static string Sound125 {
            get {
                return ResourceManager.GetString("Sound125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applause.
        /// </summary>
        internal static string Sound126 {
            get {
                return ResourceManager.GetString("Sound126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunshot.
        /// </summary>
        internal static string Sound127 {
            get {
                return ResourceManager.GetString("Sound127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xylophone.
        /// </summary>
        internal static string Sound13 {
            get {
                return ResourceManager.GetString("Sound13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubular Bells.
        /// </summary>
        internal static string Sound14 {
            get {
                return ResourceManager.GetString("Sound14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dulcimer.
        /// </summary>
        internal static string Sound15 {
            get {
                return ResourceManager.GetString("Sound15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawbar Organ.
        /// </summary>
        internal static string Sound16 {
            get {
                return ResourceManager.GetString("Sound16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percussive Organ.
        /// </summary>
        internal static string Sound17 {
            get {
                return ResourceManager.GetString("Sound17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Organ.
        /// </summary>
        internal static string Sound18 {
            get {
                return ResourceManager.GetString("Sound18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church Organ.
        /// </summary>
        internal static string Sound19 {
            get {
                return ResourceManager.GetString("Sound19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Grand Piano.
        /// </summary>
        internal static string Sound2 {
            get {
                return ResourceManager.GetString("Sound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reed Organ.
        /// </summary>
        internal static string Sound20 {
            get {
                return ResourceManager.GetString("Sound20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accordion.
        /// </summary>
        internal static string Sound21 {
            get {
                return ResourceManager.GetString("Sound21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonica.
        /// </summary>
        internal static string Sound22 {
            get {
                return ResourceManager.GetString("Sound22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tango Accordion.
        /// </summary>
        internal static string Sound23 {
            get {
                return ResourceManager.GetString("Sound23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Guitar (nylon).
        /// </summary>
        internal static string Sound24 {
            get {
                return ResourceManager.GetString("Sound24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Guitar (steel).
        /// </summary>
        internal static string Sound25 {
            get {
                return ResourceManager.GetString("Sound25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Guitar (jazz).
        /// </summary>
        internal static string Sound26 {
            get {
                return ResourceManager.GetString("Sound26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Guitar (clean).
        /// </summary>
        internal static string Sound27 {
            get {
                return ResourceManager.GetString("Sound27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Guitar (muted.
        /// </summary>
        internal static string Sound28 {
            get {
                return ResourceManager.GetString("Sound28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdriven Guitar.
        /// </summary>
        internal static string Sound29 {
            get {
                return ResourceManager.GetString("Sound29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honky-tonk Piano.
        /// </summary>
        internal static string Sound3 {
            get {
                return ResourceManager.GetString("Sound3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distortion Guitar.
        /// </summary>
        internal static string Sound30 {
            get {
                return ResourceManager.GetString("Sound30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar harmonics.
        /// </summary>
        internal static string Sound31 {
            get {
                return ResourceManager.GetString("Sound31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Bass.
        /// </summary>
        internal static string Sound32 {
            get {
                return ResourceManager.GetString("Sound32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Bass (finger).
        /// </summary>
        internal static string Sound33 {
            get {
                return ResourceManager.GetString("Sound33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Bass (pick).
        /// </summary>
        internal static string Sound34 {
            get {
                return ResourceManager.GetString("Sound34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fretless Bass.
        /// </summary>
        internal static string Sound35 {
            get {
                return ResourceManager.GetString("Sound35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slap Bass 1.
        /// </summary>
        internal static string Sound36 {
            get {
                return ResourceManager.GetString("Sound36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slap Bass 2.
        /// </summary>
        internal static string Sound37 {
            get {
                return ResourceManager.GetString("Sound37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synth Bass 1.
        /// </summary>
        internal static string Sound38 {
            get {
                return ResourceManager.GetString("Sound38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synth Bass 2.
        /// </summary>
        internal static string Sound39 {
            get {
                return ResourceManager.GetString("Sound39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Piano 1.
        /// </summary>
        internal static string Sound4 {
            get {
                return ResourceManager.GetString("Sound4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violin.
        /// </summary>
        internal static string Sound40 {
            get {
                return ResourceManager.GetString("Sound40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viola.
        /// </summary>
        internal static string Sound41 {
            get {
                return ResourceManager.GetString("Sound41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cello.
        /// </summary>
        internal static string Sound42 {
            get {
                return ResourceManager.GetString("Sound42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrabass.
        /// </summary>
        internal static string Sound43 {
            get {
                return ResourceManager.GetString("Sound43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tremolo Strings.
        /// </summary>
        internal static string Sound44 {
            get {
                return ResourceManager.GetString("Sound44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizzicato Strings.
        /// </summary>
        internal static string Sound45 {
            get {
                return ResourceManager.GetString("Sound45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestral Harp.
        /// </summary>
        internal static string Sound46 {
            get {
                return ResourceManager.GetString("Sound46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timpani.
        /// </summary>
        internal static string Sound47 {
            get {
                return ResourceManager.GetString("Sound47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Ensemble 1.
        /// </summary>
        internal static string Sound48 {
            get {
                return ResourceManager.GetString("Sound48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Ensemble 2.
        /// </summary>
        internal static string Sound49 {
            get {
                return ResourceManager.GetString("Sound49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Piano 2.
        /// </summary>
        internal static string Sound5 {
            get {
                return ResourceManager.GetString("Sound5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynthStrings 1.
        /// </summary>
        internal static string Sound50 {
            get {
                return ResourceManager.GetString("Sound50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynthStrings 2.
        /// </summary>
        internal static string Sound51 {
            get {
                return ResourceManager.GetString("Sound51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choir Aahs.
        /// </summary>
        internal static string Sound52 {
            get {
                return ResourceManager.GetString("Sound52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Oohs.
        /// </summary>
        internal static string Sound53 {
            get {
                return ResourceManager.GetString("Sound53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synth Voice.
        /// </summary>
        internal static string Sound54 {
            get {
                return ResourceManager.GetString("Sound54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestra Hit.
        /// </summary>
        internal static string Sound55 {
            get {
                return ResourceManager.GetString("Sound55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trumpet.
        /// </summary>
        internal static string Sound56 {
            get {
                return ResourceManager.GetString("Sound56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trombone.
        /// </summary>
        internal static string Sound57 {
            get {
                return ResourceManager.GetString("Sound57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuba.
        /// </summary>
        internal static string Sound58 {
            get {
                return ResourceManager.GetString("Sound58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Trumpet.
        /// </summary>
        internal static string Sound59 {
            get {
                return ResourceManager.GetString("Sound59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harpsichord.
        /// </summary>
        internal static string Sound6 {
            get {
                return ResourceManager.GetString("Sound6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Horn.
        /// </summary>
        internal static string Sound60 {
            get {
                return ResourceManager.GetString("Sound60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brass Section.
        /// </summary>
        internal static string Sound61 {
            get {
                return ResourceManager.GetString("Sound61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynthBrass 1.
        /// </summary>
        internal static string Sound62 {
            get {
                return ResourceManager.GetString("Sound62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynthBrass 2.
        /// </summary>
        internal static string Sound63 {
            get {
                return ResourceManager.GetString("Sound63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soprano Sax.
        /// </summary>
        internal static string Sound64 {
            get {
                return ResourceManager.GetString("Sound64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto Sax.
        /// </summary>
        internal static string Sound65 {
            get {
                return ResourceManager.GetString("Sound65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenor Sax.
        /// </summary>
        internal static string Sound66 {
            get {
                return ResourceManager.GetString("Sound66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baritone Sax.
        /// </summary>
        internal static string Sound67 {
            get {
                return ResourceManager.GetString("Sound67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oboe.
        /// </summary>
        internal static string Sound68 {
            get {
                return ResourceManager.GetString("Sound68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Horn.
        /// </summary>
        internal static string Sound69 {
            get {
                return ResourceManager.GetString("Sound69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clavi.
        /// </summary>
        internal static string Sound7 {
            get {
                return ResourceManager.GetString("Sound7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bassoon.
        /// </summary>
        internal static string Sound70 {
            get {
                return ResourceManager.GetString("Sound70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarinet.
        /// </summary>
        internal static string Sound71 {
            get {
                return ResourceManager.GetString("Sound71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piccolo.
        /// </summary>
        internal static string Sound72 {
            get {
                return ResourceManager.GetString("Sound72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flute.
        /// </summary>
        internal static string Sound73 {
            get {
                return ResourceManager.GetString("Sound73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder.
        /// </summary>
        internal static string Sound74 {
            get {
                return ResourceManager.GetString("Sound74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Flute.
        /// </summary>
        internal static string Sound75 {
            get {
                return ResourceManager.GetString("Sound75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blown Bottle.
        /// </summary>
        internal static string Sound76 {
            get {
                return ResourceManager.GetString("Sound76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shakuhachi.
        /// </summary>
        internal static string Sound77 {
            get {
                return ResourceManager.GetString("Sound77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whistle.
        /// </summary>
        internal static string Sound78 {
            get {
                return ResourceManager.GetString("Sound78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocarina.
        /// </summary>
        internal static string Sound79 {
            get {
                return ResourceManager.GetString("Sound79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celesta.
        /// </summary>
        internal static string Sound8 {
            get {
                return ResourceManager.GetString("Sound8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 1 (square).
        /// </summary>
        internal static string Sound80 {
            get {
                return ResourceManager.GetString("Sound80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 2 (sawtooth).
        /// </summary>
        internal static string Sound81 {
            get {
                return ResourceManager.GetString("Sound81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 3 (calliope).
        /// </summary>
        internal static string Sound82 {
            get {
                return ResourceManager.GetString("Sound82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 4 (chiff).
        /// </summary>
        internal static string Sound83 {
            get {
                return ResourceManager.GetString("Sound83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 5 (charang).
        /// </summary>
        internal static string Sound84 {
            get {
                return ResourceManager.GetString("Sound84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 6 (voice).
        /// </summary>
        internal static string Sound85 {
            get {
                return ResourceManager.GetString("Sound85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 7 (fifths).
        /// </summary>
        internal static string Sound86 {
            get {
                return ResourceManager.GetString("Sound86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead 8 (bass + lead).
        /// </summary>
        internal static string Sound87 {
            get {
                return ResourceManager.GetString("Sound87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 1 (new age).
        /// </summary>
        internal static string Sound88 {
            get {
                return ResourceManager.GetString("Sound88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 2 (warm).
        /// </summary>
        internal static string Sound89 {
            get {
                return ResourceManager.GetString("Sound89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glockenspiel.
        /// </summary>
        internal static string Sound9 {
            get {
                return ResourceManager.GetString("Sound9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 3 (polysynth).
        /// </summary>
        internal static string Sound90 {
            get {
                return ResourceManager.GetString("Sound90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 4 (choir).
        /// </summary>
        internal static string Sound91 {
            get {
                return ResourceManager.GetString("Sound91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 5 (bowed).
        /// </summary>
        internal static string Sound92 {
            get {
                return ResourceManager.GetString("Sound92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 6 (metallic).
        /// </summary>
        internal static string Sound93 {
            get {
                return ResourceManager.GetString("Sound93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 7 (halo).
        /// </summary>
        internal static string Sound94 {
            get {
                return ResourceManager.GetString("Sound94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad 8 (sweep).
        /// </summary>
        internal static string Sound95 {
            get {
                return ResourceManager.GetString("Sound95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 1 (rain).
        /// </summary>
        internal static string Sound96 {
            get {
                return ResourceManager.GetString("Sound96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 2 (soundtrack).
        /// </summary>
        internal static string Sound97 {
            get {
                return ResourceManager.GetString("Sound97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 3 (crystal).
        /// </summary>
        internal static string Sound98 {
            get {
                return ResourceManager.GetString("Sound98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX 4 (atmosphere).
        /// </summary>
        internal static string Sound99 {
            get {
                return ResourceManager.GetString("Sound99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A strongly typed class must be used for this object..
        /// </summary>
        internal static string StronglyTypedClass {
            get {
                return ResourceManager.GetString("StronglyTypedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SysEx {0} | {1} bytes.
        /// </summary>
        internal static string SysExEventFormat {
            get {
                return ResourceManager.GetString("SysExEventFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Event.
        /// </summary>
        internal static string TextEvent {
            get {
                return ResourceManager.GetString("TextEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Resolution (ticks per frame):.
        /// </summary>
        internal static string TicksPerFrame {
            get {
                return ResourceManager.GetString("TicksPerFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks per _quarter note:.
        /// </summary>
        internal static string TicksPerQuarterNote {
            get {
                return ResourceManager.GetString("TicksPerQuarterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Time-code-based time.
        /// </summary>
        internal static string TimeCodeBasedTime {
            get {
                return ResourceManager.GetString("TimeCodeBasedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Signature.
        /// </summary>
        internal static string TimeSignature {
            get {
                return ResourceManager.GetString("TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track chunk.
        /// </summary>
        internal static string TrackChunk {
            get {
                return ResourceManager.GetString("TrackChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown chunk type.
        /// </summary>
        internal static string UnknownChunkType {
            get {
                return ResourceManager.GetString("UnknownChunkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized data: &quot;{0}&quot;.
        /// </summary>
        internal static string UnrecognizedDataFormat {
            get {
                return ResourceManager.GetString("UnrecognizedDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be one of the following values:.
        /// </summary>
        internal static string ValueListFormat {
            get {
                return ResourceManager.GetString("ValueListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string ValueRangeFormat {
            get {
                return ResourceManager.GetString("ValueRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
    }
}
